all:
  hosts:
    production:
      ansible_host: 162.222.34.121
      ansible_user: tdx2
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('/tmp/deploy-key', true) }}"
  vars:
    dd_env: production
    agent_memory: 200G
    agent_cpus: 48
    agent_node_size: llm
    vfio_device: "0d:00.0"
